CoreEticaret/Areas/Admin/Controllers/AdminProductController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace CoreEticaret.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class AdminProductController : Controller
	{
		ProductManager productManager = new ProductManager(new EfProductRepository());
        Context db = new Context();
		public IActionResult Index()
		{
			var productList = productManager.GetList();
			return View(productList);
		}



        [HttpGet]
        public ActionResult AddProduct()
        {
            ViewBag.ParentId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult AddProduct(Product product)
        {
            //cm.CategoryAddBL(cat);
            ProductValidator categoryValidator = new ProductValidator();
            ValidationResult result = categoryValidator.Validate(product);
            if (result.IsValid)//sonuç geçerliyse
            {
                product.Status = true;
                product.Slider = true;
                //product.ParentId = 0;
                productManager.TAdd(product);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        //[HttpGet]
        //public ActionResult EditProduct(int? id)
        //{
        //    var cat = db.Categories.FirstOrDefault(x => x.Id == id);
        //    var categories = db.Categories.Select(x => new SelectListItem()
        //    {
        //        Text = x.Name,
        //        Value = x.Id.ToString()
        //    }).ToList();
        //    categories.Add(new SelectListItem()
        //    {
        //        Value = "0",
        //        Text = "Ana Kategori",
        //        Selected = true
        //    });
        //    ViewBag.Categories = categories;
        //    return View(cat);
        //}
        //[HttpPost]
        //public ActionResult EditProduct(Category cat)
        //{
        //    //cm.CategoryAddBL(cat);
        //    CategoryValidator categoryValidator = new CategoryValidator();
        //    ValidationResult result = categoryValidator.Validate(cat);
        //    if (result.IsValid)//sonuç geçerliyse
        //    {
        //        cat.Status = true;
        //        cat.ParentCategory = null;
        //        categoryManeger.TUpdate(cat);
        //        return RedirectToAction("Index");
        //    }
        //    else
        //    {
        //        foreach (var item in result.Errors)
        //        {
        //            ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
        //        }
        //    }
        //    return View();
        //}

        public ActionResult DeleteProduct(int? id)
        {
            var product = db.Products.FirstOrDefault(x => x.Id == id);
            productManager.TDelete(product);
            return RedirectToAction("Index");
        }
	}
}

CoreEticaret/Areas/Admin/Views/AdminProduct/AddProduct.cshtml
@model EntityLayer.Concrete.Product

@{
    ViewData["Title"] = "AddProduct";
    Layout = "~/Areas/Admin/Views/Shared/_AdminPanelLayout.cshtml";
}

<h1>Ürün Ekle</h1>

<hr />




<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("AddProduct", "AdminProduct", "Admin", FormMethod.Post))
        {
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <label for="validationCustom01">Ürün Adı</label>
                    @Html.TextBoxFor(x=>x.Name,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Name,"", new { @class = "text-danger" })
                    @*  <input type="text" class="form-control" id="validationDefault01" name="WriterName" placeholder="" required="">*@
                </div>
                <div class="col-md-6 mb-3">
                    <label for="validationCustom02">Açıklama</label>
                    @Html.TextBoxFor(x=>x.Description,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Description,"", new { @class = "text-danger" })
                    @* <input type="email" class="form-control" id="validationDefault02" name="WriterMail" placeholder="" required="">*@
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <label for="validationCustom01">Ürün Fiyatı</label>
                    @Html.TextBoxFor(x=>x.Price,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Price,"", new { @class = "text-danger" })
                    @*  <input type="text" class="form-control" id="validationDefault01" name="WriterName" placeholder="" required="">*@
                </div>
                <div class="col-md-6 mb-3">
                    <label for="validationCustom02">Stok Miktarı</label>
                    @Html.TextBoxFor(x=>x.Stock,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Stock,"", new { @class = "text-danger" })
                    @* <input type="email" class="form-control" id="validationDefault02" name="WriterMail" placeholder="" required="">*@
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <label for="validationCustom01">Ana Resim</label>
                    @Html.TextBoxFor(x=>x.Image,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image,"", new { @class = "text-danger" })
                    @*  <input type="text" class="form-control" id="validationDefault01" name="WriterName" placeholder="" required="">*@
                </div>
                <div class="col-md-6 mb-3">
                    <label for="validationCustom02">Resim 1</label>
                    @Html.TextBoxFor(x=>x.Image1,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image1,"", new { @class = "text-danger" })
                    @* <input type="email" class="form-control" id="validationDefault02" name="WriterMail" placeholder="" required="">*@
                </div>
            </div>
            <div class="form-row">
                <div class="col-md-6 mb-3">
                    <label for="validationCustom01">Resim 2</label>
                    @Html.TextBoxFor(x=>x.Image2,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image2,"", new { @class = "text-danger" })
                    @*  <input type="text" class="form-control" id="validationDefault01" name="WriterName" placeholder="" required="">*@
                </div>
                <div class="col-md-6 mb-3">
                    <label for="validationCustom02">Resim 3</label>
                    @Html.TextBoxFor(x=>x.Image3,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.Image3,"", new { @class = "text-danger" })
                    @* <input type="email" class="form-control" id="validationDefault02" name="WriterMail" placeholder="" required="">*@
                </div>
            </div>
              <div class="form-row">
                <div class="col-md-6 mb-3">
                    <label for="validationCustom01">Kategori</label>
                    @Html.TextBoxFor(x=>x.CategoryId,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.CategoryId,"", new { @class = "text-danger" })
                    @*  <input type="text" class="form-control" id="validationDefault01" name="WriterName" placeholder="" required="">*@
                </div>
                <div class="col-md-6 mb-3">
                    <label for="validationCustom02">Alt Kategori</label>
                    @* @Html.DropDownList("ParentId", null, htmlAttributes: new { @class = "form-control"  })*@
                    @Html.TextBoxFor(x=>x.ParentId,new {@class="form-control"})
                    @Html.ValidationMessageFor(x=>x.ParentId,"", new { @class = "text-danger" })
                    @* <input type="email" class="form-control" id="validationDefault02" name="WriterMail" placeholder="" required="">*@
                </div>
            </div>
            <button type="submit" class="btn btn-primary submit mb-4">Ürün Ekle</button>
        }
    </div>
</div>

<div>
    <a href="/Admin/AdminProduct/Index/">Ürün Listesine Dön</a>
</div>

CoreEticaret/Areas/Admin/Views/AdminProduct/Index.cshtml
@using EntityLayer.Concrete
@model List<Product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminPanelLayout.cshtml";
}

<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">

            <div class="card-tools">
                <a class="btn btn-primary" href="/Admin/AdminProduct/AddProduct/">Yeni Ürün Ekle</a>

            </div>

        </div>
        <div class="card-body p-0">
            <table class="table table-striped projects">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Resim</th>
                        <th>Ürün Adı</th>
                        <th>Açıklama</th>
                        <th>Fiyat</th>
                        <th>Stok</th>

                        <th>Slider</th>
                        <th>Durum</th>
                        <th>Parent ID</th>
                        <th>Kategori</th>
                        <th>İşlemler</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.Id
                            </td>
                            <td>
                                <img src="@item.Image" width=50 height=50>
                            </td>
                            <td>
                                    @item.Name
                            </td>
                            <td>
                                @item.Description
                            </td>


                            <td>@item.Price</td>
                            <td>@item.Stock</td>

                            @* <td>@item.Image1</td>*@
                            @* <td>@item.Image2</td>*@
                            @* <td>@item.Image3</td>*@
                            @if (item.Slider == true)
                            {
                                <td>
                                    <span class="badge badge-success">Aktif</span>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <span class="badge badge-danger">Pasif</span>
                                </td>
                            }


                            @if (item.Status == true)
                            {
                                <td class="project-state">
                                    <span class="badge badge-success">Aktif</span>
                                </td>
                            }
                            else
                            {
                                <td class="project-state">
                                    <span class="badge badge-danger">Pasif</span>
                                </td>
                            }
                            <td>@item.ParentId</td>
                            <td>@item.CategoryId</td>
                            <td class="project-actions text-right">
                                <a class="btn btn-info btn-sm" href="/Admin/AdminProduct/EditProduct/@item.Id/">
                                    <i class="fas fa-pencil-alt">
                                    </i>
                                    Düzenle
                                </a>
                                <a class="btn btn-danger btn-sm" href="/Admin/AdminProduct/DeleteProduct/@item.Id/">
                                    <i class="fas fa-trash">
                                    </i>
                                    Sil
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

</section>