CoreEticaret/Models/Cart.cs
using EntityLayer.Concrete;
using System.Collections.Generic;
using System.Linq;

namespace CoreEticaret.Models
{
    public class Cart//alışveriş sepetinin tamamını temsil eder
    {
        private List<Cartline> _cartLines = new List<Cartline>();
        public List<Cartline> Cartlines
        {
            get { return _cartLines; }
        }
        public void AddProduct(Product product, int quantity)
        {
            var line = _cartLines.FirstOrDefault(i => i.Product.Id == product.Id);
            if (line == null)
            {
                _cartLines.Add(new Cartline() { Product = product, Quantity = quantity });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        public void DeleteProduct(Product product)
        {
            _cartLines.RemoveAll(i => i.Product.Id == product.Id);
        }
        public double Total()
        {
            return _cartLines.Sum(i => i.Product.Price * i.Quantity);
        }
        public void Clear()
        {
            _cartLines.Clear();
        }
    }
    public class Cartline//alışveriş sepetindeki bir satırı temsil eder
    {
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

CoreEticaret/Controllers/CartController.cs
using CoreEticaret.Models;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CoreEticaret.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart

        Context db = new Context();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddToCart(int Id)//karta ekle
        {
            //ürünü veri tabanına kaydet
            var product = db.Products.FirstOrDefault(i => i.Id == Id);
            Summary sum = new Summary();
            sum.ProductId = product.Id;
            sum.Name = product.Name;
            sum.Price = product.Price;
            sum.Stock = product.Stock;
            sum.musteriID = product.Stock;
        

            if (product != null)//eğer ürün veri tabanında var ise
            {
                db.Summaries.Add(sum);
                db.SaveChanges();
            }
            return RedirectToAction("ShopCart", "Product");
        }
        public ActionResult RemoveFromCart(int Id)//karttan sil
        {
            //ürünü veri tabanından sil
            var summary = db.Summaries.FirstOrDefault(i => i.Id == Id);
            if (summary != null)//eğer ürün veri tabanında var ise
            {
                db.Summaries.Remove(summary);
                db.SaveChanges();
            }
            return RedirectToAction("ShopCart", "Product");
        }

        public PartialViewResult Summary()
        {
            return PartialView();
        }
        /**/

        public ActionResult AddressList()
        {
            var addres = db.Addresses.Where(u => u.UserName == User.Identity.Name).ToList();
            return View(addres);
        }
        public ActionResult CreateUserAddress()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateUserAddress(Address entity)
        {
            entity.UserName = User.Identity.Name;

            db.Addresses.Add(entity);
            db.SaveChanges();
            return RedirectToAction("AddressList");
        }

        public ActionResult DeleteUserAddress(int id)
        {
            Address addres = db.Addresses.Find(id);
            db.Addresses.Remove(addres);
            db.SaveChanges();
            return RedirectToAction("AddressList");
        }

        /**/
        public ActionResult PayList(int id)
        {
            Pay pay = new Pay();
            TempData["Adressid"] = id;
            pay.AddressID = id;
            db.Pays.Add(pay);
            //var pays = db.Pays.Where(u => u.AddressID == pay.AddressID).ToList();
            return View(db.Pays.Where(u => u.AddressID == pay.AddressID).ToList());
        }
        public ActionResult CreateUserPay()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateUserPay(Pay entity, int id)
        {
            if (ModelState.IsValid)
            {
                entity.UserName = User.Identity.Name;
                entity.AddressID = id;
                db.Pays.Add(entity);
                db.SaveChanges();
                return RedirectToAction("PayList/" + entity.AddressID);
            }
            else
            {
                return View(entity);
            }

        }

        public ActionResult DeleteUserPay(int id)
        {
            Pay pay = db.Pays.Find(id);
            db.Pays.Remove(pay);
            db.SaveChanges();
            return RedirectToAction("PayList/" + pay.AddressID);
        }

        //public ActionResult CreateOrder()
        //{
        //    return View(new Addres());
        //}
        public ActionResult CreateOrder(List<Address> entity, List<Pay> entity1, int id, int payid)
        {
            //sepetteki ürün ile sipariş oluşturma..
            //var cart = GetCart();
            //if (/*cart.Cartlines.Count == 0*/)
            //{
                ModelState.AddModelError("UrunYokError", "Sepetinizde ürün bulunmamaktadır..");
            //}
            if (ModelState.IsValid)//sepette ürün var ise
            {
                //SaveOrder(cart, entity, entity1, id, payid);
                //veri tabanına kaydet
                //cart.Clear();
                // return View("Complated");

                return RedirectToAction("Complated");
            }
            else
            {
                return View(entity1);
            }
        }
        private void SaveOrder(Cart cart, List<Address> entity, List<Pay> entity1, int id, int payid)
        {
            var order = new Order();
            order.OrderNumber = "A" + (new Random()).Next(1111, 9999).ToString();//a harfi ile başlayan 4 haneli bir sipariş numarası 
            order.Total = cart.Total();
            order.OrderDate = DateTime.Now;
            order.OrderState = EnumOrderState.Bekleniyor;
            order.UserName = User.Identity.Name;
            order.UserAddressID = id;
            order.PayID = payid;

            order.OrderLines = new List<OrderLine>();
            foreach (var pr in cart.Cartlines)
            {
                var orderline = new OrderLine();
                orderline.Quantity = pr.Quantity;
                orderline.Price = pr.Quantity * pr.Product.Price;
                orderline.ProductId = pr.Product.Id;
                orderline.Stock = pr.Product.Stock - orderline.Quantity;//
                order.OrderLines.Add(orderline);
            }

            db.Orders.Add(order);
            db.SaveChanges();
        }

        /**/
        //public ActionResult Checkout()
        //{
        //    return View(new ShippingDetails());
        //}

        //[HttpPost]
        //public ActionResult Checkout(ShippingDetails entity)
        //{
        //    var cart = GetCart();
        //    if (cart.Cartlines.Count == 0)
        //    {
        //        ModelState.AddModelError("UrunYokError", "Sepetinizde ürün bulunmamaktadır..");
        //    }
        //    if (ModelState.IsValid)//sepette ürün var ise
        //    {
        //        SaveOrder(cart, entity);
        //        //veri tabanına kaydet
        //        cart.Clear();
        //        //return View("Complated");

        //        return RedirectToAction("Complated");
        //    }
        //    else
        //    {
        //        return View(entity);
        //    }

        //}

        //private void SaveOrder(Cart cart, ShippingDetails entity)
        //{
        //    var order = new Order();
        //    order.OrderNumber = "A" + (new Random()).Next(1111, 9999).ToString();//a harfi ile başlayan 4 haneli bir sipariş numarası 
        //    order.Total = cart.Total();
        //    order.OrderDate = DateTime.Now;
        //    order.OrderState = EnumOrderState.Bekleniyor;
        //    order.UserName = User.Identity.Name;
        //    order.AdresBasligi = entity.AdresBasligi;
        //    order.Adres = entity.Adres;
        //    order.Il = entity.Il;
        //    order.Ilce = entity.Ilce;
        //    order.Mahalle = entity.Mahalle;
        //    order.PostaKodu = entity.PostaKodu;
        //    /*kart bilgileri*/
        //    order.CartNumber = entity.CartNumber;
        //    order.SecurityNumber = entity.SecurityNumber;
        //    order.CartHasName = entity.CartHasName;
        //    order.ExpYear = entity.ExpYear;
        //    order.ExpMonth = entity.ExpMonth;
        //    /**/
        //    order.OrderLines = new List<OrderLine>();
        //    foreach (var pr in cart.Cartlines)
        //    {
        //        var orderline = new OrderLine();
        //        orderline.Quantity = pr.Quantity;
        //        orderline.Price = pr.Quantity * pr.Product.Price;
        //        orderline.ProductId = pr.Product.Id;
        //        orderline.Stock = pr.Product.Stock - orderline.Quantity;//
        //        order.OrderLines.Add(orderline);
        //    }

        //    db.Orders.Add(order);
        //    db.SaveChanges();
        //}

        public ActionResult Complated()
        {
            var username = User.Identity.Name;
            var orders = db.Orders.Where(i => i.UserName == username).Select(i => new UserOrderModel
            {
                Id = i.Id,
                OrderNumber = i.OrderNumber,
                OrderDate = i.OrderDate,
                OrderState = i.OrderState,
                Total = i.Total
            }).OrderByDescending(i => i.OrderDate).ToList();//azalan olarak sıraladık yani en son verilen sipariş en başa gelir.
            return View(orders);
            //orders tablosundaki bilgileri userOrderModel tablosunun içerisine paketledik
        }
        public ActionResult Details(int id)
        {
            var entity = db.Orders.Where(i => i.Id == id).Select(i => new OrderDetailsModel()
            {
                OrderId = i.Id,
                OrderNumber = i.OrderNumber,
                Total = i.Total,
                OrderDate = i.OrderDate,
                OrderState = i.OrderState,
                AdresBasligi = i.Addres.AdresBasligi,
                Adres = i.Addres.Adres,
                Il = i.Addres.Il,
                Ilce = i.Addres.Ilce,
                Mahalle = i.Addres.Mahalle,
                PostaKodu = i.Addres.PostaKodu,
                UserAddressID = i.UserAddressID,
                /*kart bilgileri*/
                CartNumber = i.Pay.CartNumber,
                SecurityNumber = i.Pay.SecurityNumber,
                CartHasName = i.Pay.CartHasName,
                ExpYear = i.Pay.ExpYear,
                ExpMonth = i.Pay.ExpMonth,
                /**/
                OrderLines = i.OrderLines.Select(x => new OrderLineModel()
                {
                    ProductId = x.ProductId,
                    Image = x.Product.Image,
                    ProductName = x.Product.Name,

CoreEticaret/Views/Cart/AddressList.cshtml
@model IEnumerable<EntityLayer.Concrete.Address>
@{
    ViewData["Title"] = "AddressList";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<div id="mainBody">
    <div class="container">
        <div class="row">
            <div class="span12">


                <h2>Adres Seçimi</h2>

                <p>
                    <img src="~/Content/Images/home.png" width="25" height="25" />@Html.ActionLink("Yeni Adres Ekle", "CreateUserAddress")
                </p>
                <table class="table table-hover">
                    <tr>
                        <th></th>
                        <th>
                            @Html.DisplayNameFor(model => model.AdresBasligi)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Adres)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Il)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Ilce)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Mahalle)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PostaKodu)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <img src="~/Content/Images/home.png" width="25" height="25" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AdresBasligi)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Adres)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Il)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Ilce)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PostaKodu)
                            </td>
                            <td>
                                @*@using (Html.BeginForm("CreateOrder", "Cart"))
                                    {
                                        @Html.HiddenFor(modelItem => item.Id)
                                        <button type="submit" class="btn btn-large btn-primary pull-right">Varsayılan Adres Seç<i class=" icon-shopping-cart"></i></button>
                                    }*@
                                @*@Html.ActionLink("Sil", "DeleteUserAddress", new { id = item.Id }, new { @class = "btn btn-medium btn-danger " }) |*@
                                @*@Html.ActionLink("Varsayılan Adres Seç", "CreateOrder", new { id = item.Id }, new { @class = "btn btn-medium btn-primary" })*@
                                <a href="/Cart/DeleteUserAddress/@item.Id" class="btn btn-danger">Sil</a>

                                <a href="/Cart/PayList/@item.Id" class="btn btn-success">Adres Seç <i class="icon-arrow-right"></i></a>


                                @*<a href="/Cart/CreateOrder/@item.Id" class="btn btn-success">Alışverişi Tamamla <i class="icon-arrow-right"></i></a>*@

                            </td>
                        </tr>
                    }

                </table>



            </div>


        </div>
    </div>
</div>

CoreEticaret/Views/Cart/CreateUserAddress.cshtml
@model CoreEticaret.Models.ApplicationUser

@{
    ViewData["Title"] = "CreateUserAddress";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div id="mainBody">
    <div class="container">
        <div class="row">
            <div class="span12">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <h4>Yeni Adres</h4>
                    <hr />
                    <div class="jumbotron" style="margin-left:32%;">


                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="form-group">
                            @Html.LabelFor(model => model.AdresBasligi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.AdresBasligi, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.AdresBasligi, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Il, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Il, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Il, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Ilce, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Ilce, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Ilce, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.Mahalle, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Mahalle, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Mahalle, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.PostaKodu, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PostaKodu, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PostaKodu, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Ekle" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }

            </div>


        </div>
    </div>
</div>

CoreEticaret/Views/Cart/Summary.cshtml
@*@model CoreEticaret.Models.Cart*@

<ul class="header__right__widget">
    <li><span class="icon_search search-switch"></span></li>
    <li>

        <a href="#">

            <span class="icon_heart_alt"></span>
            <div class="tip">2</div>
        </a>

    </li>
    <li>
      @*  /Cart/Index *@
        <a href="/Product/ShopCart/">

            <span class="icon_bag_alt"></span>
            <div class="tip">1</div>
        </a>

    </li>
</ul>